const num = 15;

try {
	num = 20;
} catch (err) {
	console.log('Erro gerado:', err);
}
